indexing-settings:
  sites:
#    - url: https://lenta.ru/
#      name: Лента.ру
    - url: https://skillbox.ru/
      name: Skillbox
#    - url: https://playback.ru/
#      name: PlayBack.Ru

#    - url: https://disneyland.disney.go.com/
#      name: DisneyLand
    - url: https://eng.rudn.ru/
      name: PFUoR
#    - url: https://sciencedirect.com/
#      name: Science Direct
  batchsize: 1000

config:
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
  referrer: https://google.com

server:
  port: 8080

spring:
#  aop:
#    proxy-target-class: false
#  thymeleaf:
#    prefix: classpath:/templates/
  redis:
    host: localhost
    port: 6379
  http:
    log-request-details: true
  mvc:
    view:
      suffix: .html
#  jackson:
#    serialization:
#      fail-on-empty-beans: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/search_engine
  jpa:
    mapping:
      - class: searchengine.model.Site
      - class: searchengine.model.Page
      - class: searchengine.model.Lemma
      - class: searchengine.model.Index
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        jdbc:
          batch_size: 1000
          order_inserts: true
          order_deletes: true
          order_updates: true
        generate_statistics: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: trace
    request-details: trace
  config:
    classpath: log4j2.xml