indexing-settings:
  sites:
    - url: https://lenta.ru/
      name: Лента.ру
    - url: https://skillbox.ru/
      name: Skillbox
    - url: https://baliforum.ru/
      name: Bali Forum
    - url: https://nikoartgallery.com/
      name: Арт галерея Niko

config:
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
  referrer: https://google.com

server:
  port: 8080
  error:
    whitelabel:
      enabled: true
    path: /error

spring:
#  aop:
#    proxy-target-class: false
  mvc:
    view:
      suffix: .html
    log-request-details: true
#  jackson:
#    serialization:
#      fail-on-empty-beans: false
  sql:
    init:
      mode: never
      schema-locations: classpath:schema-postgresql.sql
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/search_engine?currentSchema=search_engine
    username: postgres
    password: 12345678
  jpa:
    hibernate:
      ddl-auto: update
    mapping:
      - class: searchengine.model.Site
      - class: searchengine.model.Page
      - class: searchengine.model.Lemma
      - class: searchengine.model.Index
    properties:
      hibernate:
        default_schema: search_engine
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        jdbc:
          batch_size: 2500
          order_inserts: true
          order_deletes: true
          order_updates: true
          generate_statistics: false
    show-sql: true
    open-in-view: false
#  session:
#    factory_class: org.hibernate.boot.spi.SessionFactoryOptions
  web:
    locale: ru
    locale-resolver: fixed
    resources:
      static-locations:
        classpath: /templates/
  thymeleaf:
      prefix:
        classpath: /templates/
  messages:
      basename: lang.messages

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: info
    request-details: info
  config:
    classpath: log4j2.xml