indexing-settings:
  sites:
    - url: https://lenta.ru/
      name: Лента.ру
    - url: https://skillbox.ru/
      name: Skillbox
    - url: https://playback.ru/
      name: PlayBack.Ru

config:
  userAgent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
  referrer: https://google.com

server:
  port: 8080

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false&requireSSL=false&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    mapping:
      - class: searchengine.model.Site
      - class: searchengine.model.Page
      - class: searchengine.model.Lemma
      - class: searchengine.model.Index

logging:
  level:
    org.springframework.web.servlet.DispatcherServlet: trace
    request-details: trace
  config:
    classpath: src/main/resources/log4j2.xml